### ISSUE TITLE
Can we use Laravel-websockets

### ISSUE THREAD

**Issue by evidencefrank** [mirovit/nova-notifications#21]
Good Day,

I was wondering if its possible to use Laravel-websockets as an alternative to Pusher?

**Comment by mirovit** [comment]
Hello @evidencefrank,

This package does not rely on a specific implementation, since it uses the built-in Laravel features for sending and receiving messages using Echo - it says on the official Laravel Docs that it supports this case - https://laravel.com/docs/8.x/broadcasting#open-source-alternatives

You just need to configure your application to use the new driver and all should work as expected. I've used Pusher in the doc examples, because I used it during development, but you're not limited to just using it.

**Comment by evidencefrank** [comment]
Thanks @mirovit ,
I had forgotten to create the "notifications" table while doing the setup.
